// Shared patch engine for the Zero3 desktop source overlays.
//
// Every overlay is replayed over whatever the previous run left behind -- a
// generated Electron tree, a tree that was generated by an older overlay set,
// or a tree this same overlay already patched. Three properties keep that
// replay honest, and they are the only reason this module exists instead of a
// pair of `source.replace()` calls in each overlay:
//
//   * idempotent: a replacement is skipped only when a marker proves the
//     current shape is already in place, never because "something similar" is
//     present;
//   * fail-closed: an anchor that no longer matches raises instead of silently
//     leaving the runtime unwired, and each candidate names the exact text it
//     rewrites so a moved composition point is repaired rather than duplicated;
//   * no duplicate injection: invariants assert the post-conditions (defined
//     once, wired once) before anything is written back to disk.
export function patchOverlaySource({ relativePath, source, replacements, invariants = [], driftPrefix = 'Zero3 overlay' }) {
  let patched = source
  for (const replacement of replacements) {
    const already = [
      typeof replacement.to === 'string' ? replacement.to : null,
      replacement.appliedMarker,
      replacement.already,
      ...(replacement.alreadyAny ?? [])
    ].filter(Boolean)
    if (already.some(marker => patched.includes(marker))) continue
    // A candidate is either the text to rewrite, or `{ from, to }` when the
    // replacement depends on which shape matched -- a repaired legacy block and
    // a freshly inserted block are not the same edit. Candidates are tried in
    // order, so the narrowest shape must come first.
    const candidates = [replacement.from, ...(replacement.fromAny ?? [])]
      .filter(Boolean)
      .map(entry => (typeof entry === 'object' && !(entry instanceof RegExp) ? entry : { from: entry }))
    const candidate = candidates.find(entry => (entry.from instanceof RegExp ? entry.from.test(patched) : patched.includes(entry.from)))
    if (!candidate) {
      throw new Error(
        `${driftPrefix} drift in ${relativePath}: missing ${replacement.label}.` +
          (replacement.hint ? ` ${replacement.hint}` : '')
      )
    }
    const replacementText = candidate.to ?? replacement.to
    patched = patched.replace(candidate.from, match =>
      typeof replacementText === 'function' ? replacementText(match) : replacementText
    )
  }
  assertOverlayInvariants({ relativePath, source: patched, invariants, driftPrefix })
  return patched
}

export function assertOverlayInvariants({ relativePath, source, invariants = [], driftPrefix = 'Zero3 overlay' }) {
  for (const invariant of invariants) {
    const texts = invariant.texts ?? [invariant.text]
    const copies = texts.reduce((total, text) => total + source.split(text).length - 1, 0)
    if (copies !== invariant.count) {
      throw new Error(
        `${driftPrefix} left ${copies} copies of ${invariant.label} in ${relativePath}; expected ${invariant.count}.`
      )
    }
  }
}
