const assert = require('node:assert/strict')
const { test } = require('node:test')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..')
const read = relative => fs.readFileSync(path.join(root, relative), 'utf8')

test('session list distinguishes active, idle, stalled, connection loss, timeout recovery, and unread-complete states', () => {
  const list = read('ui-v2/conversations/UnifiedSessionList.tsx')
  assert.match(list, /session\.executionHealth \?\? \(executing \? 'active' : null\)/)
  assert.match(list, /data-session-health/)
  assert.match(list, /border-emerald-500/)
  assert.match(list, /border-amber-500/)
  assert.match(list, /border-red-500/)
  assert.match(list, /motion-safe:animate-ping/)
  assert.match(list, /等待进展/)
  assert.match(list, /疑似卡住/)
  assert.match(list, /发送超时/)
  assert.match(list, /连接中断/)
  assert.match(list, /自动恢复 1\/1/)
  assert.match(list, /准备换会话/)
  assert.match(list, /切换新会话/)
  assert.match(list, /换会话失败/)
  assert.match(list, /completionUnread && !executing/)
  assert.match(list, /bg-red-500/)
})

test('local turns still report execution start and completion to the unified shell', () => {
  const surface = read('ui-v2/conversations/LocalConversationSurface.tsx')
  const shell = read('ui-v2/shell/Zero3AppShell.tsx')
  assert.match(surface, /onExecutionChange\(session\.id, true\)/)
  assert.match(surface, /onExecutionChange\(session\.id, false\)/)
  assert.match(shell, /executingLocalSessionIds\.has\(record\.id\)/)
})
test('finished background sessions stay unread until their page is viewed', () => {
  const shell = read('ui-v2/shell/Zero3AppShell.tsx')
  const types = read('ui-v2/conversations/session-types.ts')
  assert.match(types, /completionUnread\?: boolean/)
  assert.match(shell, /SESSION_COMPLETION_UNREAD_STORAGE_KEY/)
  assert.match(shell, /persistCompletionUnreadSessionIds/)
  assert.match(shell, /previous === true && !status\.executing/)
  assert.match(shell, /viewedSessionIdRef\.current !== sessionId/)
  assert.match(shell, /setSessionCompletionUnread\(session\.id, false\)/)
})

test('GPT and Gemini web providers maintain a mutation heartbeat without copying response text', () => {
  const gpt = read('gpt-web-runtime/gpt-web-provider.ts')
  const gemini = read('gemini-web-runtime/gemini-web-provider.ts')
  for (const source of [gpt, gemini]) {
    assert.match(source, /EXECUTION_PROBE_INTERVAL_MS = 800/)
    assert.match(source, /EXECUTION_IDLE_AFTER_MS = 90_000/)
    assert.match(source, /EXECUTION_STALLED_AFTER_MS = 5 \* 60_000/)
    assert.match(source, /__zero3ExecutionWatchdogV1/)
    assert.match(source, /new MutationObserver/)
    assert.match(source, /lastProgressAt/)
    assert.match(source, /health = idleForMs >= EXECUTION_STALLED_AFTER_MS \? 'stalled'/)
  }
})
test('web execution health is carried through the renderer adapter', () => {
  const adapter = read('ui-v2/adapters/WebWorkspaceAdapter.ts')
  const types = read('ui-v2/conversations/session-types.ts')
  const shell = read('ui-v2/shell/Zero3AppShell.tsx')
  assert.match(types, /'timeout_error'/)
  assert.match(types, /'connection_lost'/)
  assert.match(types, /'recovering'/)
  assert.match(types, /'recovery_failed'/)
  assert.match(types, /'rotating'/)
  assert.match(types, /'rotation_failed'/)
  assert.match(types, /executionHealth\?: WorkspaceExecutionHealth \| null/)
  assert.match(adapter, /executionHealth: execution\.health/)
  assert.match(adapter, /lastProgressAt: execution\.lastProgressAt/)
  assert.match(adapter, /idleForMs: event\.idleForMs/)
  assert.match(shell, /executionHealth: status\.health/)
  assert.match(shell, /executionIdleForMs: status\.idleForMs/)
})

test('GPT timeout recovery classifies the error locally and never opens Ctrl+F', () => {
  const gpt = read('gpt-web-runtime/gpt-web-provider.ts')
  assert.match(gpt, /消息发送超时/)
  assert.match(gpt, /TIMEOUT_RECOVERY_PROMPT = '现在完成到哪一步了？如果还没完成，请继续执行'/)
  assert.match(gpt, /TIMEOUT_RECOVERY_DELAY_MS = 3_000/)
  assert.match(gpt, /TIMEOUT_LOCKED_ROTATION_DELAY_MS = 15_000/)
  assert.match(gpt, /MAX_TIMEOUT_PHYSICAL_ROTATIONS = 1/)
  assert.match(gpt, /TIMEOUT_ROTATION_PROMPT = '刚才的会话因消息发送超时或连接中断并且已经无法继续交互/)
  assert.match(gpt, /archivePreRotationConversation/)
  assert.match(gpt, /conversationUrl: null/)
  assert.match(gpt, /rotatePhysicalConversation/)
  assert.match(gpt, /scheduleTimeoutRotation/)
  assert.match(gpt, /timeoutRecoveryStates/)
  assert.match(gpt, /phase: 'scheduled' \| 'recovering' \| 'failed'/)
  assert.match(gpt, /composerText\(composer\)\.trim\(\)/)
  assert.match(gpt, /data-testid=\"send-button\"/)
  assert.doesNotMatch(gpt, /findInPage|window\.find|execCommand\(['"]find/i)
})

test('GPT connection-lost detection is debounced and uses the existing recovery/rotation path', () => {
  const gpt = read('gpt-web-runtime/gpt-web-provider.ts')
  const shell = read('ui-v2/shell/Zero3AppShell.tsx')
  assert.match(gpt, /连接已中断/)
  assert.match(gpt, /waiting for \(\?:the \)\?full response/i)
  assert.match(gpt, /connectionLostHits/)
  assert.match(gpt, /connectionLostHits >= 3/)
  assert.match(gpt, /health: 'connection_lost'/)
  assert.match(gpt, /isRecoverableFailureHealth/)
  assert.match(gpt, /TIMEOUT_LOCKED_ROTATION_DELAY_MS = 15_000/)
  assert.match(gpt, /MAX_TIMEOUT_PHYSICAL_ROTATIONS = 1/)
  assert.match(gpt, /boundProjectUrl\(entry\.projectId\)/)
  assert.match(shell, /status\.health === 'connection_lost'/)
  assert.doesNotMatch(gpt, /findInPage|window\.find|OCR/i)
})

test('generated preload type overlays expose provider-specific health contracts', () => {
  const gpt = read('scripts/apply-gpt-web-provider.mjs')
  const gemini = read('scripts/apply-gemini-web-provider.mjs')
  assert.match(gpt, /'timeout_error' \| 'connection_lost' \| 'recovering' \| 'recovery_failed' \| 'rotating' \| 'rotation_failed'/)
  assert.match(gpt, /recoveryAttempt: 0 \| 1/)
  assert.match(gemini, /health: 'active' \| 'idle' \| 'stalled' \| null/)
  for (const source of [gpt, gemini]) {
    assert.match(source, /lastProgressAt: number \| null/)
    assert.match(source, /idleForMs: number/)
  }
})
