const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const root = path.resolve(__dirname, '..')
const surface = fs.readFileSync(path.join(root, 'ui-v2/conversations/Zero3NativeConversationSurface.tsx'), 'utf8')
const types = fs.readFileSync(path.join(root, 'ui-v2/conversations/session-types.ts'), 'utf8')
const store = fs.readFileSync(path.join(root, 'ui-v2/adapters/Zero3SessionEventStore.ts'), 'utf8')
const runtime = fs.readFileSync(path.join(root, 'scripts/apply-session-provider-runtime.mjs'), 'utf8')
const renderer = fs.readFileSync(path.join(root, 'ui-v2/codex/CodexItemRenderer.tsx'), 'utf8')
const list = fs.readFileSync(path.join(root, 'ui-v2/codex/CodexMessageList.tsx'), 'utf8')
test('runtime config follows Codex model metadata instead of a fixed four-effort list', () => {
  assert.match(surface, /zero3Codex\.model\.list/)
  assert.match(surface, /supportedReasoningEfforts/)
  assert.match(surface, /defaultReasoningEffort/)
  assert.match(surface, /serviceTiers/)
  assert.match(surface, /defaultServiceTier/)
  assert.match(surface, /nextCursor/)
  assert.match(types, /'minimal'.*'xhigh'.*'max'.*'ultra'/)
  assert.match(runtime, /serviceTier\?: string \| null/)
  assert.match(runtime, /\.\.\.\(options\.serviceTier \? \{ serviceTier: options\.serviceTier \} : \{\}\)/)
  assert.match(surface, /serviceTier: session\.serviceTier/)
})
test('native timeline reuses the real Codex item renderer and ships no mock turns', () => {
  assert.match(renderer, /Zero3SessionEvent/)
  assert.match(renderer, /commandExecution/)
  assert.match(renderer, /fileChange/)
  assert.match(renderer, /mcpToolCall/)
  assert.match(list, /events\.map\(event => <CodexItemRenderer/)
  assert.doesNotMatch(list, /mockTurns|Mock Data/)
})

test('runtime binding persists service tier together with model and effort', () => {
  assert.match(store, /serviceTier: string \| null/)
  assert.match(store, /serviceTier: session\.serviceTier/)
  assert.match(store, /serviceTier: binding\.serviceTier/)
})
